apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipfsweb7
spec:
  selector:
    matchLabels:
      app: ipfsweb7
  replicas: 1
  template:
    metadata:
      labels:
        app: ipfsweb7
    spec:
      containers:
      - name: ipfsweb7
        image: 9221484790/ipfswebui:v7
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: ipfsweb7
spec:
 type: NodePort
 selector:
   app: ipfsweb7
 ports:
   - name: client
     protocol: TCP
     port: 80
     nodePort: 32085
 selector:
   app: ipfsweb7
 type: LoadBalancer
