apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipfsbackend
spec:
  selector:
    matchLabels:
      app: ipfsbackend
  replicas: 1
  template:
    metadata:
      labels:
        app: ipfsbackend
    spec:
      containers:
      - name: ipfsbackend
        image: 9221484790/ipfswebui:v7
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: ipfsbackend
spec:
 type: NodePort
 selector:
   app: ipfsbackend
 ports:
   - name: client
     protocol: TCP
     port: 80
     nodePort: 330900
 selector:
   app: ipfsbackend
 type: LoadBalancer
