apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipfsfrontend
spec:
  selector:
    matchLabels:
      app: ipfsfrontend
  replicas: 1
  template:
    metadata:
      labels:
        app: ipfsfrontend
    spec:
      containers:
      - name: ipfsfrontend
        image: 9221484790/ipfswebui:v7
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: ipfsfrontend
spec:
 type: NodePort
 selector:
   app: ipfsfrontend
 ports:
   - name: client
     protocol: TCP
     port: 80
     nodePort: 330901
 selector:
   app: ipfsfrontend
 type: LoadBalancer